esphome:
  name: dehydrator
  platform: ESP8266
  board: esp01_1m

wifi: !include wifi.yaml

api:

logger:

ota:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "dehydrator-button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "dehydrator-switch"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

