esphome:
  name: dryer_fan
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

# Disable logging over USB
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      name: "Dryer Fan Current"
    voltage:
      name: "Dryer Fan Voltage"
    power:
      name: "Dryer Fan Power"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Pow R2 Button"
    on_press:
      - switch.toggle: relay
      
switch:
  - platform: gpio
    name: "Dryer Fan"
    pin: GPIO12
    id: relay
    inverted: no
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: yes
