substitutions:
  device_name: counter_2
  friendly_name: Counter 2

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

api:

ota:

power_supply:
  - id: rgb_power
    pin: GPIO13

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_component2
    pin: GPIO12

light: !include feit_rgbw.yaml
