substitutions:
  device_name: merkury_br30_2
  friendly_name: Morning Alarm 2

<<: !include fccid/2AJ3WEBESHW01.yaml

time:
  - platform: sntp
    timezone: Etc/UTC
    id: sntp_time
    on_time:
      # Every morning on weekdays
      - seconds: 00
        minutes: 00
        hours: 01
        then:
          - light.turn_on: ${device_name}
      # Every morning on weekdays
      - seconds: 00
        minutes: 00
        hours: 12
        then:
          - light.turn_on: ${device_name}
