substitutions:
  device_name: tub
  device_id: tub
  friendly_name: Tub

<<: !include ../../fccid/SYW-PLUGWIFI.yaml

script:
  - id: "${device_id}_auto_off"
    mode: restart
    then:
      - delay: 10min
      - switch.turn_off: "${device_id}_relay"

switch:
# Main relay - defaults to OFF after power failure
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO12
    id: "${device_id}_relay"
    restore_mode: RESTORE_DEFAULT_OFF
    # Automatically shut off after 10 minutes when turned on (non-blocking)
    on_turn_on:
      - script.execute: "${device_id}_auto_off"
    # Stop the auto-off script if manually turned off
    on_turn_off:
      - script.stop: "${device_id}_auto_off"

