api:
  reboot_timeout:
    hours: 24

ota:
  platform: esphome

web_server:
  port: 80

# Example configuration entry
time:
  - platform: sntp
    timezone: Etc/EST
    id: sntp_time
    servers:
      - 192.168.0.20
      - 192.168.0.30
    # Daily restart automation removed - devices that need this should override
    # the time section in their device-specific configs (see hotwater_plug.yaml)
        
sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    id: ${device_id}_signal

text_sensor:
  - platform: version
    name: ${friendly_name} Version
    id: ${device_id}_version
  
  # WiFi information sensors using built-in wifi_info component (no lambdas)
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
      id: ${device_id}_ip
    ssid:
      name: ${friendly_name} WiFi SSID
      id: ${device_id}_ssid
    bssid:
      name: ${friendly_name} WiFi BSSID
      id: ${device_id}_bssid
    mac_address:
      name: ${friendly_name} WiFi MAC
      id: ${device_id}_mac
<<: !include wifi.yaml
